### ISSUE TITLE
Resources 'ready' trigger not called if list of resources to load is empty

### ISSUE THREAD

**Issue by Harry-OBrien** [TomHsiao1260/three-starter#12]
If an empty list of textures/models are requested to be loaded, i.e. `this.loader.load([]);`, `this.loader.on('end', fn)` is never called and thus `resources.on('ready', fn)` is never called. Default behaviour should be to fire the 'ready' trigger if `Loader::load(_resources)` is called with an empty list.

**Comment by TomHsiao1260** [comment]
Hi, Harry

Thanks for checking it carefully. I'll send a fix for this issue later. Really appreciate it!

**Comment by TomHsiao1260** [comment]
fixed, thanks.

**Comment by TomHsiao1260** [comment]
Note: It's a bit tricky to find a solution to trigger `.on('ready', ...)` if the resources loading time is near instant because in such condition `.trigger('ready')` will be executed in advance (before `.on` event). Maybe the current solution is not perfect but at least it make the rest of the code operate normally. Feel free to let me know if you have any better solution. If so, you can send me a PR or I'll reopen this issue for further discussion, thanks!
