### ISSUE TITLE
Support for webXR?

### ISSUE THREAD

**Issue by kubam1414** [TomHsiao1260/three-starter#14]
Hi guys!
I'm starting new project for VR and I'm wondering how to combine this template with WebXR.

My struggle is how to set it up with SetAnimtionLoop which is required for WebXr project.

Any suggestions?

**Comment by TomHsiao1260** [comment]
Hi, Kubam

Glad to know this template may help you building your own project. I'm not familar with VR related works. But if you want to use SetAnimtionLoop instead of requestAnimationFrame, the simplest way is to delete the following two lines in `Time.js`:

[delete this](https://github.com/TomHsiao1260/three-starter/blob/main/src/javascript/Utils/Time.js#L16): `this.tick();`
[delete this](https://github.com/TomHsiao1260/three-starter/blob/main/src/javascript/Utils/Time.js#L28): `this.ticker = window.requestAnimationFrame(this.tick);`

And then add the following line at the bottom of setRenderer method in `Application.js` to set the animation loop:
```
    setRenderer() {
        ...
        this.renderer.setAnimationLoop(this.time.tick);
    }
```

Would like to know whether this solution works on your project. Also, feel free to let me know if you have any further issues or suggestions, thanks!

**Comment by kubam1414** [comment]
Yep, that worked for me.
Thanks!
