### ISSUE TITLE
Vite + Typescript

### ISSUE THREAD

**Issue by theRenard** [TomHsiao1260/three-starter#8]
Hi, I like your OOP approach, are you interested in a PR with vite and typescript? I have a prototype already working

**Comment by TomHsiao1260** [comment]
That sounds good to me, really appreciate it.

However, there are still some developers familiar with Vanilla JS & Webpack. Can I put your efforts in another GitHub branch so that others still can see the original script in main branch (Vanilla JS & Webpack)? If it's okay for you, I'll update the relevant description in the Readme for those who want to use Vite with Typescript as well.

Feel free to let me know if you have any thoughts. Thanks in advance.

**Comment by theRenard** [comment]
Sure, sound good for me 👌
